// Generated by gencpp from file mrobot_navigation/Sbs.msg
// DO NOT EDIT!


#ifndef MROBOT_NAVIGATION_MESSAGE_SBS_H
#define MROBOT_NAVIGATION_MESSAGE_SBS_H

#include <ros/service_traits.h>


#include <mrobot_navigation/SbsRequest.h>
#include <mrobot_navigation/SbsResponse.h>


namespace mrobot_navigation
{

struct Sbs
{

typedef SbsRequest Request;
typedef SbsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sbs
} // namespace mrobot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrobot_navigation::Sbs > {
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::mrobot_navigation::Sbs&) { return value(); }
};

template<>
struct DataType< ::mrobot_navigation::Sbs > {
  static const char* value()
  {
    return "mrobot_navigation/Sbs";
  }

  static const char* value(const ::mrobot_navigation::Sbs&) { return value(); }
};


// service_traits::MD5Sum< ::mrobot_navigation::SbsRequest> should match
// service_traits::MD5Sum< ::mrobot_navigation::Sbs >
template<>
struct MD5Sum< ::mrobot_navigation::SbsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrobot_navigation::Sbs >::value();
  }
  static const char* value(const ::mrobot_navigation::SbsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrobot_navigation::SbsRequest> should match
// service_traits::DataType< ::mrobot_navigation::Sbs >
template<>
struct DataType< ::mrobot_navigation::SbsRequest>
{
  static const char* value()
  {
    return DataType< ::mrobot_navigation::Sbs >::value();
  }
  static const char* value(const ::mrobot_navigation::SbsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrobot_navigation::SbsResponse> should match
// service_traits::MD5Sum< ::mrobot_navigation::Sbs >
template<>
struct MD5Sum< ::mrobot_navigation::SbsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrobot_navigation::Sbs >::value();
  }
  static const char* value(const ::mrobot_navigation::SbsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrobot_navigation::SbsResponse> should match
// service_traits::DataType< ::mrobot_navigation::Sbs >
template<>
struct DataType< ::mrobot_navigation::SbsResponse>
{
  static const char* value()
  {
    return DataType< ::mrobot_navigation::Sbs >::value();
  }
  static const char* value(const ::mrobot_navigation::SbsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MROBOT_NAVIGATION_MESSAGE_SBS_H
