// Generated by gencpp from file state_machine/StateResponse.msg
// DO NOT EDIT!


#ifndef STATE_MACHINE_MESSAGE_STATERESPONSE_H
#define STATE_MACHINE_MESSAGE_STATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_machine
{
template <class ContainerAllocator>
struct StateResponse_
{
  typedef StateResponse_<ContainerAllocator> Type;

  StateResponse_()
    : state(0)  {
    }
  StateResponse_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::state_machine::StateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_machine::StateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StateResponse_

typedef ::state_machine::StateResponse_<std::allocator<void> > StateResponse;

typedef boost::shared_ptr< ::state_machine::StateResponse > StateResponsePtr;
typedef boost::shared_ptr< ::state_machine::StateResponse const> StateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_machine::StateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_machine::StateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_machine::StateResponse_<ContainerAllocator1> & lhs, const ::state_machine::StateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_machine::StateResponse_<ContainerAllocator1> & lhs, const ::state_machine::StateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_machine

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::StateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::StateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_machine::StateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_machine::StateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::StateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::StateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_machine::StateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "800f34bc468def1d86e2d42bea5648c0";
  }

  static const char* value(const ::state_machine::StateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x800f34bc468def1dULL;
  static const uint64_t static_value2 = 0x86e2d42bea5648c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::state_machine::StateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_machine/StateResponse";
  }

  static const char* value(const ::state_machine::StateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_machine::StateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 state\n"
;
  }

  static const char* value(const ::state_machine::StateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_machine::StateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_machine::StateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_machine::StateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_MACHINE_MESSAGE_STATERESPONSE_H
