// Generated by gencpp from file state_machine/StateRequest.msg
// DO NOT EDIT!


#ifndef STATE_MACHINE_MESSAGE_STATEREQUEST_H
#define STATE_MACHINE_MESSAGE_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_machine
{
template <class ContainerAllocator>
struct StateRequest_
{
  typedef StateRequest_<ContainerAllocator> Type;

  StateRequest_()
    {
    }
  StateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::state_machine::StateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_machine::StateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StateRequest_

typedef ::state_machine::StateRequest_<std::allocator<void> > StateRequest;

typedef boost::shared_ptr< ::state_machine::StateRequest > StateRequestPtr;
typedef boost::shared_ptr< ::state_machine::StateRequest const> StateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_machine::StateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_machine::StateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace state_machine

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::StateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::StateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_machine::StateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_machine::StateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::StateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::StateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_machine::StateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::state_machine::StateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::state_machine::StateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_machine/StateRequest";
  }

  static const char* value(const ::state_machine::StateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_machine::StateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::state_machine::StateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_machine::StateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_machine::StateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::state_machine::StateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STATE_MACHINE_MESSAGE_STATEREQUEST_H
